# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  listseerr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listseerr
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - ./data:/app/data
    env_file:
      - .env.docker
    user: '${UID:-1000}:${GID:-1000}'
