# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  listseerr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listseerr
    user: ${PUID:-1000}:${PGID:-1000}
    ports:
      - ${PORT:-3000}:3000
    env_file:
      # copy from deploy/.env.example
      - .env.docker
    volumes:
      - ./data:/app/data
    restart: unless-stopped
