version: '3.8'

services:
  listseerr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listseerr
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    user: '${UID:-1000}:${GID:-1000}'
