# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
services:
  listseerr:
    image: ghcr.io/guillevc/listseerr:latest
    container_name: listseerr
    ports:
      - 3000:${PORT}
    environment:
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${TZ}
      # (REQUIRED) Used for database encryption of API keys
      # Generate with: openssl rand -hex 32
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
